spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: 081ed8bdb52e02ec585662f119bb8f0f
          naver:
            client-id: _dEdJ6FFCGgGMoxABMTk
            client-secret: TFBz0zf5Ht
          google:
            client-id: 197219319903-4io0ov5ajeben9a65vbq8fqiihcb14et.apps.googleusercontent.com
            client-secret: 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