spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: 081ed8bdb52e02ec585662f119bb8f0f

kakao:
  map:
    api-key: 30cc897c2f8058664580d99144c54422