spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: 23aea9a1c65852062852136b4fa7fa19
          naver:
            client-id: _dEdJ6FFCGgGMoxABMTk
            client-secret: cMH21v9t5q
          google:
            client-id: 197219319903-4io0ov5ajeben9a65vbq8fqiihcb14et.apps.googleusercontent.com
            client-secret: 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

kakao:
  map:
    api-key: 10eaa715b47bf05113704c5663fbfa93

